config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # utiliza padrao de arquitetura rest
  # ja cria todas as rotas padrao 
  # TODO entender essa funcionalidade resources
  # TODO pesquisar como fazer desenvolvido web sem o rails
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resource cria as rotas rest 
  # only define as rotas rest o user vai poder acessar
  resources :users, only: [:new, :create, :show]

  # Defines the root path route ("/")
  # root "articles#index"
  
  # paginas estaticas => nao tem crud
  root to: "static_pages#index"

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  get 'sair', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  # busca os atributos do schema

  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true

  # pertence ao usuario
  # associação
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # cria um hash da senha
  # cria dois atributos virtuais password e password_confirmation
  has_secure_password 

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  # validacoes
  # validates => método de validacao de modulo
  # presence => obrigatorio
  # length => maximo de caracteres
  # case_sensetive => checa se a string está com caixa alta, caixa baixa

  validates :nome, presence: true, length: { maximum: 50}
  validates :password, length: { maximum: 6 }
  validates :email, presence: true, 
    length: {maximum: 255}, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensetive: true }

  # usuario tem mts contatos, associação
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # todos os controller herda esse metodo do helper
    include SessionsHelper

    private 
        def require_logged_in_user
            # unless ???
            unless user_signed_in?
                flash[:danger] = 'Área restrita. Por favor, realize o login'  
                redirect_to entrar_path 
            end
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # vai ser executado antes de toda acao, vai ver se o usuario ta logado, se nn manda ele loga
  before_action :require_logged_in_user 
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    # constroi um objt com os parametros de contato
    @contact = current_user.contacts.build(contact_params) 

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # entender esses parametros nas rotas
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create 
    # fazer um teste o que vem nesse params

    user = User.find_by(email: params[:session][:email].downcase)

    # method do has_secure_password
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      # redirecionamento
      # passa  a rota show passando o usuario
      # redireciona para lista de contatos

      redirect_to contacts_path
    else
      # flash.now 
      # se usar só flash vai ficar persistida por mais uma requisicao
      flash.now[:danger] = 'Email ou senha invalidos'
      # renderiza a view new
      render 'new'
    end
  end

  def destroy
    sign_out 
    flash[:success] = 'Logout realizado com sucesso'
    redirect_to entrar_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index 
   @nome = "Nathan"
  end

# funcao deve ter medo do layout
  def sobre

  end

  def contato
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new
  end

  def create    
    # tras os paranemtnos da requisicao(body)
    @user = User.new(user_params)
    # TODO entender como é por tras da ORM ActiveRecord
    # TODO pesquisar criação de api com rails
    # TODO o que é haml
    # TODO entender melhor as syntax das funcoes
    if @user.save
      # flash => envia menagem para o usuario
      flash[:success] = 'Usuário cadatrado com sucesso'
      # redireciona o usuario para a pagina root(index)
      redirect_to root_url
    else
      # redireciona o usuario para a pagina de cadastro novamente
      render 'new'
    end
  end

  # padrao do ruby
  private def user_params 
    # garante que apenas esses paramentos sao inseridos no usuario
    params.require(:user).permit(:email, :nome, :password, :password_confirmation)
    # TODO pesquisar como realizar esses processo de forma manual 
    # TODO como é a função params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def sign_in(user_id) 
    # variavel session, disponibiliza session do browser
    # tipo um hash, cria chave => valor
    # guarda usuario na session
    session[:user_id] = user_id
   end

   def sign_out
    # apaga a session do usuario
    session.delete(:user_id)
   end

   # normalmente usado no ruby, algumas gems usam
   def current_user 
    # ||= se a variavel ja for setada, nao faz a query 
    # se for nil ele seta, fazendo a query

    @current_user ||= User.find_by(id: session[:user_id])
   end

   # se nn for nil retorna true, se n retorna false

   def user_signed_in?
    !current_user.nil?
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  # auxilia na repeticao de codigo
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/layouts/_error_messages.html.erb
<!-- object.erros.any => verifica se ha erros --->
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
    <!-- pluralize => se erros.count for mais de um ele retorna erros se nn ele retorna erro --->
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
      <ul>
      <!-- full_messages => array de erros --->
        <% object.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. Todos os direitos reservados.', root_path %>
  </small>
  <nav>
    <ul>
      <li>
      <!-- vai ser gerado uma tag <a>
        rails gera essa urls, tira sobre_path do caminho routs
      --->

        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  <nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
      </div>

    <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
    <div class="collapse navbar-collapse" id="expanded-menu">
      <ul class="nav navbar-nav">
      <% if !user_signed_in? %>
        <li class="active">
          <%= link_to 'Nova Conta', new_user_path %>
        </li>
      <%end%>
      </ul>

      <ul class="nav navbar-nav navbar-right">

      <% if !user_signed_in? %>
        <li>
          <%= link_to 'Entrar', entrar_path %>
        </li>
      <%else%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              bem vindo<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Minha Pagina', current_user%>
              </li>
            <li>
                <%= link_to 'Editar', "#" %>
            </li>
            <li class="divider" role="separator"></li>
            <li>
                <%= link_to 'Sair', sair_path, method: :delete %>
            </li>
          </ul>
        </li>
    <%end%>
    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <!-- flash => elemento mensagem a ser exibida -->
      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert=dismissible", role: 'alert' do %> 
          <button type="button" class="close" data-dismiss="alert" arial-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>
      <!-- o que vem de controller --->
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>
<p>
  Entre em contato com <a href="http://wwww.twitter.com/nathan">@nathan</a> para saber mais
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Contact List</h1>
  <p>
    Gerencie seus contatos em qualquer lugar!
  </p>
  <p>
    <%= link_to 'Crie Sua Conta', new_user_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>
<p>
  Estudos ruby
</p>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Cadastra-se</h1> 
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for @user do |f| %>
      <!-- f.object => é o user --->
      <%= render 'layouts/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :nome %>
        <%= f.text_field :nome, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
   <% end %>
  <div>
</div>

app/views/users/show.html.erb
<%=current_user.name%>